######List of Command######
#' A list of R commands as the table of content
#' @export
command<- function(){
  cat("\014")
  cat(bold$inverse("\nList of Command\n"))
  cat('\n')
  cat(bold$underline('Setting up the environment: setup()'), fill = 1)
  cat('\n \t')
  cat('install()......install a package', fill = 1)
  cat('\n \t')
  cat('lib()..........load a library', fill = 1)
  cat('\n \t')
  cat('read().........Read in a data set', fill = 1)
  cat('\n')
  cat(bold$underline('Data cleaning and manipulation: clean()'), fill = 1)
  cat('\n \t')
  cat('naming().......Name objects', fill = 1)
  cat('\n \t')
  cat('dataframe()....Create a data frame', fill = 1)
  cat('\n')
  cat(bold$underline('Life saving packages: lifesaver()'), fill = 1)
  cat('\n \t')
  cat(bold('dplyr package: DplyR()'), fill = 1)
  cat('\n \t\t')
  cat('tbl()..........Convert a data frame to tibble', fill = 1)
  cat('\n')
  cat(bold$underline('APA formatting and style: APA()'), fill = 1)
  cat('\n \t')
  cat('APAjournal()...Cite a journal article in APA style', fill = 1)
  cat('\n')
  cat(bold$underline('Cheat sheet builder: csbuilder()'), fill = 1)
  cat('\n')
  cat(bold$underline('Package Update Diary: diary()'), fill = 1)
  cat('\n\n')
  ask()
}
