######List of Command######
#' A list of R commands as the table of content
#' @export
command<- function(){
  cat(rep("\n", 20))
  cat(bold$inverse("\nList of Command\n"))
  cat('\n')
  cat(bold$underline('Setting up environment: setup()'), fill = 1)
  cat('\n \t')
  cat('install()......template for installing a package', fill = 1)
  cat('\n \t')
  cat('lib()..........template for loading in a library', fill = 1)
  cat('\n \t')
  cat('read().........template for reading in a data set', fill = 1)
  cat('\n')
  cat(bold$underline('Data cleaning and manipulation: clean()'), fill = 1)
  cat('\n \t')
  cat('naming().......template for naming objects', fill = 1)
  cat('\n \t')
  cat('dataframe()....template for creating a data frame', fill = 1)
  cat('\n \t')
  cat('tbl()..........template for converting a data frame to tibble', fill = 1)
  cat('\n')
  cat(bold$underline('APA formatting and style: APA()'), fill = 1)
  cat('\n \t')
  cat('APAjournal()...template for citing a journal article in APA style', fill = 1)
  cat('\n')
  cat(bold$underline('Package Update Diary: diary()'), fill = 1)
  cat('\n \t')
  cat('July072019()')
  cat('\n \t')
  cat('July082019()')
  cat('\n \t')
  cat('July092019()')
  cat('\n \t')
  cat('July102019()')
  cat('\n\n')
  ask()
}
