######List of Command######
#' A list of R commands as the table of content
#' @export
command<- function(){
  cat("\014")
  cat(bold$inverse("\nList of Cheat Sheet\n"))
  cat('\n')
  cat(bold$underline('Setting up the environment: setup()'), fill = 1)
  cat('\n \t')
  cat('cs_install()......Install a package', fill = 1)
  cat('\n \t')
  cat('cs_library()..........Load a library', fill = 1)
  cat('\n \t')
  cat('cs_read().........Read in a data set', fill = 1)
  cat('\n')
  cat(bold$underline('Data wrangling: wrangle()'), fill = 1)
  cat('\n \t')
  cat('cs_name().......Name objects', fill = 1)
  cat('\n \t')
  cat('cs_data.frame()....Create a data frame', fill = 1)
  cat('\n')
  cat(bold$underline('Life saving packages: lifesaver()'), fill = 1)
  cat('\n \t')
  cat(bold('dplyrpkg(): dplyr package'), fill = 1)
  cat('\n \t\t')
  cat('cs_tbl()..........Convert a data frame to tibble', fill = 1)
  cat('\n')
  cat(bold$underline('Cheat sheet building tools: builder()'), fill = 1)
  cat('\n \t')
  cat('csbuilder().......Cheat Sheet Builder', fill = 1)
  cat('\n \t')
  cat('menubuilder().......Menu Builder', fill = 1)
  cat('\n \t')
  cat('linkbuilder().......Link Builder', fill = 1)
  cat('\n')
  cat(bold$underline('Package Update Diary: diary()'), fill = 1)
  cat('\n\n')
  ask()
}
